Repository Mrcolin99/stretch-dogs, pull requests merged in 2023-01, with the labels that each got.

#22 Justen/feat/questionnaire
  src/components/Main/Main.js
  src/components/Questionnaire/Questionnaire.css
  src/components/Questionnaire/Questionnaire.js
Labels: enhancement, FE

#50 Tricia/feature/add fetch
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Main/Main.js
  src/components/Questionnaire/Questionnaire.js
  src/components/Results/Results.js
  src/utilis/constants.js
Labels: enhancement, help wanted, FE, PR PENDING

#51 Fix rendering issues on results page
  src/components/Results/Results.js
Labels: FE, PR PENDING

#52 Header, footer, and questionnaire styling
  package-lock.json
  package.json
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Main/Main.css
  src/components/Questionnaire/Questionnaire.css
  src/components/Questionnaire/Questionnaire.js
Labels: enhancement, FE

#67 Tricia/feature/add env
  .gitignore
  public/favicon.ico
  public/index.html
  src/utilis/constants.js
Labels: FE

#69 Tricia/feature/add details
  src/components/Main/Main.js
  src/components/Questionnaire/Questionnaire.js
  src/components/Results/Results.js
  src/utilis/apiCalls.js
  src/utilis/constants.js
Labels: enhancement, FE, PR PENDING

#77 Tricia/feature/add desc
  src/components/Card/Card.js
  src/components/Results/Results.js
Labels: enhancement, FE

#84 Tricia/feature/edit results css
  src/assets/images/dog-home.gif
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Header/Header.css
  src/components/Questionnaire/Questionnaire.js
  src/components/Resources/Resources.js
  src/components/Results/Results.css
  src/utilis/apiCalls.js
Labels: FE

#85 Tricia/feature/edit cypress
  cypress/e2e/error_spec.cy.js
  cypress/e2e/main.cy.js
  cypress/e2e/questionnaire.cy.js
  cypress/e2e/results.cy.js
  cypress/fixtures/single_dog.json
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Questionnaire/Questionnaire.js
  src/components/Results/Results.css
Labels: FE
